# syntax=docker/dockerfile:1
# check=error=true

FROM oven/bun:1.3-alpine

# copy over everything (excl. ``.dockerignore``)
WORKDIR /tbsp
COPY . .

# vite attempts to call node, which doesn't exist
# bun will try to install node in the docker container, which
# hangs for whatever reason.
# this was painful to debug.
RUN ln -s /usr/local/bin/bun /bin/node;
RUN bun install -D;
RUN bun run build-lib;
CMD ["bun", "dev"]
